server:
  port: 8080


demo:
  userName: luo

#解决swagger 3与Spring boot的版本兼容问题
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
#
#spring:
#  mvc:
#    pathmatch:
#      matching-strategy: ANT_PATH_MATCHER

